// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/ffi_plugin.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FfiPluginBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FfiPluginBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FfiPluginBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// =======================
  /// API для Flutter (FFI)
  /// =======================
  int load_model(
    ffi.Pointer<ffi.Char> model_path,
  ) {
    return _load_model(
      model_path,
    );
  }

  late final _load_modelPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
          'load_model');
  late final _load_model =
      _load_modelPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int run_inference(
    ffi.Pointer<ffi.Int16> pcm_data,
    int length,
  ) {
    return _run_inference(
      pcm_data,
      length,
    );
  }

  late final _run_inferencePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Int16>, ffi.Int)>>('run_inference');
  late final _run_inference =
      _run_inferencePtr.asFunction<int Function(ffi.Pointer<ffi.Int16>, int)>();

  void unload_model() {
    return _unload_model();
  }

  late final _unload_modelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('unload_model');
  late final _unload_model = _unload_modelPtr.asFunction<void Function()>();
}
